version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - start-dev
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - DB_VENDOR=postgres
      # - DB_ADDR=postgres
      # - DB_DATABASE=keycloak
      # - DB_USER=keycloak
      # - DB_PASSWORD=keycloak
      - KEYCLOAK_LOGLEVEL=DEBUG
    ports:
      - "8080:8080"
    volumes:
      - './custom-theme/theme:/opt/keycloak/themes'


volumes:
  keycloak_data:
  